### ISSUE TITLE
how to get ROOMBA_PASSWORD

### ISSUE THREAD

**Issue by Joeviocoe** [kumy/Roomba980-Wifi#2]
Both BLID and ROOMBA_PASSWORD are required to be known and entered beforehand into wifi-config.py and initial_config.py

But how do I get those values?

Is the BLID the same as the Roomba's Wifi Soft AP SSID (broadcasted after factory reset)?

NickWaterton's Roomba980-Python package does have a Password discovery feature.  But it seems like that is assuming the Roomba has already connected to Your WiFi network.

Seems like a chicken and egg problem.  
I want to connect the Roomba to my network without the app.

Thanks.

**Comment by kumy** [comment]
Yes, the BLID is derived from the wifi AP name.

You push the password you wish see https://github.com/kumy/Roomba980-Wifi/blob/master/initial-config.py#L36 . I've not played a lot with password capabilities, but if you follow the format (`:1:timestamp:16 alpha-decimal chars`) then you should be fine (and yes ; in the example code `:1:1579195386:8fx7nYqVtKgWJ9tO` IS the password - yes the full string.)

Other than the source code, the last closed issue has nice info in there https://github.com/kumy/Roomba980-Wifi/issues/1

I hope you'll success.
Please keep me posted ;)

**Comment by kumy** [comment]
@Joeviocoe did you succeed?

**Comment by Joeviocoe** [comment]
I haven't tried it yet.  I will post a comment on how well it works on my Roomba 675

**Comment by kumy** [comment]
I'll close the issue, feel free to reopen if you still have problems

**Comment by kumy** [comment]
@Joeviocoe did you finally get success?

**Comment by Joeviocoe** [comment]
Yes, it all worked as expected.
